version: '3.8'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: ${JDBC_URL}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_HOST: smtp.yandex.ru
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: ${EMAIL}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SECURITY_JWT_TOKEN_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      postgresql-db:
        condition: service_healthy

  postgresql-db:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      postgresql-db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  postgres_data:
