spring:
  profiles:
    active: prod
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

  session:
    jdbc:
      initialize-schema: always

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/swagger-ui